/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Activity = IDL.Record({
  'caloriesBurnedPerMinuteModerate' : IDL.Float64,
  'name' : IDL.Text,
  'caloriesBurnedPerMinuteFast' : IDL.Float64,
  'caloriesBurnedPerMinuteSlow' : IDL.Float64,
});
export const MealEntry = IDL.Record({
  'totalCalories' : IDL.Float64,
  'quantityGrams' : IDL.Float64,
  'foodName' : IDL.Text,
});
export const ActivitySpeed = IDL.Variant({
  'fast' : IDL.Null,
  'slow' : IDL.Null,
  'moderate' : IDL.Null,
});
export const ActivityEntry = IDL.Record({
  'activityName' : IDL.Text,
  'speed' : ActivitySpeed,
  'durationMinutes' : IDL.Float64,
  'caloriesBurned' : IDL.Float64,
});
export const DailyLog = IDL.Record({
  'meals' : IDL.Vec(MealEntry),
  'date' : IDL.Text,
  'activities' : IDL.Vec(ActivityEntry),
  'totalCaloriesBurned' : IDL.Float64,
  'totalCaloriesConsumed' : IDL.Float64,
});
export const Food = IDL.Record({
  'servingSizeGrams' : IDL.Float64,
  'caloriesPerServing' : IDL.Float64,
  'name' : IDL.Text,
  'caloriesPer100g' : IDL.Float64,
  'category' : IDL.Text,
});
export const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'heightCm' : IDL.Float64,
  'targetBmi' : IDL.Float64,
  'weightKg' : IDL.Float64,
  'targetWeightKg' : IDL.Float64,
  'gender' : Gender,
});

export const idlService = IDL.Service({
  'addActivity' : IDL.Func([Activity], [], []),
  'addDailyLog' : IDL.Func([DailyLog], [], []),
  'addFood' : IDL.Func([Food], [], []),
  'getActivity' : IDL.Func([IDL.Text], [Activity], ['query']),
  'getAllActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
  'getAllFoods' : IDL.Func([], [IDL.Vec(Food)], ['query']),
  'getDailyLogs' : IDL.Func([], [IDL.Vec(DailyLog)], ['query']),
  'getFood' : IDL.Func([IDL.Text], [Food], ['query']),
  'getUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'updateUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Activity = IDL.Record({
    'caloriesBurnedPerMinuteModerate' : IDL.Float64,
    'name' : IDL.Text,
    'caloriesBurnedPerMinuteFast' : IDL.Float64,
    'caloriesBurnedPerMinuteSlow' : IDL.Float64,
  });
  const MealEntry = IDL.Record({
    'totalCalories' : IDL.Float64,
    'quantityGrams' : IDL.Float64,
    'foodName' : IDL.Text,
  });
  const ActivitySpeed = IDL.Variant({
    'fast' : IDL.Null,
    'slow' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const ActivityEntry = IDL.Record({
    'activityName' : IDL.Text,
    'speed' : ActivitySpeed,
    'durationMinutes' : IDL.Float64,
    'caloriesBurned' : IDL.Float64,
  });
  const DailyLog = IDL.Record({
    'meals' : IDL.Vec(MealEntry),
    'date' : IDL.Text,
    'activities' : IDL.Vec(ActivityEntry),
    'totalCaloriesBurned' : IDL.Float64,
    'totalCaloriesConsumed' : IDL.Float64,
  });
  const Food = IDL.Record({
    'servingSizeGrams' : IDL.Float64,
    'caloriesPerServing' : IDL.Float64,
    'name' : IDL.Text,
    'caloriesPer100g' : IDL.Float64,
    'category' : IDL.Text,
  });
  const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'heightCm' : IDL.Float64,
    'targetBmi' : IDL.Float64,
    'weightKg' : IDL.Float64,
    'targetWeightKg' : IDL.Float64,
    'gender' : Gender,
  });
  
  return IDL.Service({
    'addActivity' : IDL.Func([Activity], [], []),
    'addDailyLog' : IDL.Func([DailyLog], [], []),
    'addFood' : IDL.Func([Food], [], []),
    'getActivity' : IDL.Func([IDL.Text], [Activity], ['query']),
    'getAllActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
    'getAllFoods' : IDL.Func([], [IDL.Vec(Food)], ['query']),
    'getDailyLogs' : IDL.Func([], [IDL.Vec(DailyLog)], ['query']),
    'getFood' : IDL.Func([IDL.Text], [Food], ['query']),
    'getUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'updateUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };