/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'caloriesBurnedPerMinuteModerate' : number,
  'name' : string,
  'caloriesBurnedPerMinuteFast' : number,
  'caloriesBurnedPerMinuteSlow' : number,
}
export interface ActivityEntry {
  'activityName' : string,
  'speed' : ActivitySpeed,
  'durationMinutes' : number,
  'caloriesBurned' : number,
}
export type ActivitySpeed = { 'fast' : null } |
  { 'slow' : null } |
  { 'moderate' : null };
export interface DailyLog {
  'meals' : Array<MealEntry>,
  'date' : string,
  'activities' : Array<ActivityEntry>,
  'totalCaloriesBurned' : number,
  'totalCaloriesConsumed' : number,
}
export interface Food {
  'servingSizeGrams' : number,
  'caloriesPerServing' : number,
  'name' : string,
  'caloriesPer100g' : number,
  'category' : string,
}
export type Gender = { 'female' : null } |
  { 'male' : null };
export interface MealEntry {
  'totalCalories' : number,
  'quantityGrams' : number,
  'foodName' : string,
}
export interface UserProfile {
  'age' : bigint,
  'heightCm' : number,
  'targetBmi' : number,
  'weightKg' : number,
  'targetWeightKg' : number,
  'gender' : Gender,
}
export interface _SERVICE {
  'addActivity' : ActorMethod<[Activity], undefined>,
  'addDailyLog' : ActorMethod<[DailyLog], undefined>,
  'addFood' : ActorMethod<[Food], undefined>,
  'getActivity' : ActorMethod<[string], Activity>,
  'getAllActivities' : ActorMethod<[], Array<Activity>>,
  'getAllFoods' : ActorMethod<[], Array<Food>>,
  'getDailyLogs' : ActorMethod<[], Array<DailyLog>>,
  'getFood' : ActorMethod<[string], Food>,
  'getUserProfile' : ActorMethod<[], UserProfile>,
  'updateUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];