/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Activity {
    caloriesBurnedPerMinuteModerate: number;
    name: string;
    caloriesBurnedPerMinuteFast: number;
    caloriesBurnedPerMinuteSlow: number;
}
export interface MealEntry {
    totalCalories: number;
    quantityGrams: number;
    foodName: string;
}
export interface DailyLog {
    meals: Array<MealEntry>;
    date: string;
    activities: Array<ActivityEntry>;
    totalCaloriesBurned: number;
    totalCaloriesConsumed: number;
}
export interface Food {
    servingSizeGrams: number;
    caloriesPerServing: number;
    name: string;
    caloriesPer100g: number;
    category: string;
}
export interface ActivityEntry {
    activityName: string;
    speed: ActivitySpeed;
    durationMinutes: number;
    caloriesBurned: number;
}
export interface UserProfile {
    age: bigint;
    heightCm: number;
    targetBmi: number;
    weightKg: number;
    targetWeightKg: number;
    gender: Gender;
}
export enum ActivitySpeed {
    fast = "fast",
    slow = "slow",
    moderate = "moderate"
}
export enum Gender {
    female = "female",
    male = "male"
}
export interface backendInterface {
    addActivity(activity: Activity): Promise<void>;
    addDailyLog(log: DailyLog): Promise<void>;
    addFood(food: Food): Promise<void>;
    getActivity(name: string): Promise<Activity>;
    getAllActivities(): Promise<Array<Activity>>;
    getAllFoods(): Promise<Array<Food>>;
    getDailyLogs(): Promise<Array<DailyLog>>;
    getFood(name: string): Promise<Food>;
    getUserProfile(): Promise<UserProfile>;
    updateUserProfile(profile: UserProfile): Promise<void>;
}
import type { ActivityEntry as _ActivityEntry, ActivitySpeed as _ActivitySpeed, DailyLog as _DailyLog, Gender as _Gender, MealEntry as _MealEntry, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addActivity(arg0: Activity): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addActivity(arg0);
            return result;
        }
    }
    async addDailyLog(arg0: DailyLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDailyLog(to_candid_DailyLog_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDailyLog(to_candid_DailyLog_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addFood(arg0: Food): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFood(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFood(arg0);
            return result;
        }
    }
    async getActivity(arg0: string): Promise<Activity> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivity(arg0);
            return result;
        }
    }
    async getAllActivities(): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActivities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActivities();
            return result;
        }
    }
    async getAllFoods(): Promise<Array<Food>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFoods();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFoods();
            return result;
        }
    }
    async getDailyLogs(): Promise<Array<DailyLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyLogs();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyLogs();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFood(arg0: string): Promise<Food> {
        if (this.processError) {
            try {
                const result = await this.actor.getFood(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFood(arg0);
            return result;
        }
    }
    async getUserProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_UserProfile_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_UserProfile_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(to_candid_UserProfile_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(to_candid_UserProfile_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_ActivityEntry_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityEntry): ActivityEntry {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_ActivitySpeed_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivitySpeed): ActivitySpeed {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_DailyLog_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyLog): DailyLog {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    meals: Array<_MealEntry>;
    date: string;
    activities: Array<_ActivityEntry>;
    totalCaloriesBurned: number;
    totalCaloriesConsumed: number;
}): {
    meals: Array<MealEntry>;
    date: string;
    activities: Array<ActivityEntry>;
    totalCaloriesBurned: number;
    totalCaloriesConsumed: number;
} {
    return {
        meals: value.meals,
        date: value.date,
        activities: from_candid_vec_n11(_uploadFile, _downloadFile, value.activities),
        totalCaloriesBurned: value.totalCaloriesBurned,
        totalCaloriesConsumed: value.totalCaloriesConsumed
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    activityName: string;
    speed: _ActivitySpeed;
    durationMinutes: number;
    caloriesBurned: number;
}): {
    activityName: string;
    speed: ActivitySpeed;
    durationMinutes: number;
    caloriesBurned: number;
} {
    return {
        activityName: value.activityName,
        speed: from_candid_ActivitySpeed_n14(_uploadFile, _downloadFile, value.speed),
        durationMinutes: value.durationMinutes,
        caloriesBurned: value.caloriesBurned
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    heightCm: number;
    targetBmi: number;
    weightKg: number;
    targetWeightKg: number;
    gender: _Gender;
}): {
    age: bigint;
    heightCm: number;
    targetBmi: number;
    weightKg: number;
    targetWeightKg: number;
    gender: Gender;
} {
    return {
        age: value.age,
        heightCm: value.heightCm,
        targetBmi: value.targetBmi,
        weightKg: value.weightKg,
        targetWeightKg: value.targetWeightKg,
        gender: from_candid_Gender_n18(_uploadFile, _downloadFile, value.gender)
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fast: null;
} | {
    slow: null;
} | {
    moderate: null;
}): ActivitySpeed {
    return "fast" in value ? ActivitySpeed.fast : "slow" in value ? ActivitySpeed.slow : "moderate" in value ? ActivitySpeed.moderate : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    female: null;
} | {
    male: null;
}): Gender {
    return "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ActivityEntry>): Array<ActivityEntry> {
    return value.map((x)=>from_candid_ActivityEntry_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DailyLog>): Array<DailyLog> {
    return value.map((x)=>from_candid_DailyLog_n9(_uploadFile, _downloadFile, x));
}
function to_candid_ActivityEntry_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityEntry): _ActivityEntry {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_ActivitySpeed_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivitySpeed): _ActivitySpeed {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_DailyLog_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DailyLog): _DailyLog {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    meals: Array<MealEntry>;
    date: string;
    activities: Array<ActivityEntry>;
    totalCaloriesBurned: number;
    totalCaloriesConsumed: number;
}): {
    meals: Array<_MealEntry>;
    date: string;
    activities: Array<_ActivityEntry>;
    totalCaloriesBurned: number;
    totalCaloriesConsumed: number;
} {
    return {
        meals: value.meals,
        date: value.date,
        activities: to_candid_vec_n3(_uploadFile, _downloadFile, value.activities),
        totalCaloriesBurned: value.totalCaloriesBurned,
        totalCaloriesConsumed: value.totalCaloriesConsumed
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    heightCm: number;
    targetBmi: number;
    weightKg: number;
    targetWeightKg: number;
    gender: Gender;
}): {
    age: bigint;
    heightCm: number;
    targetBmi: number;
    weightKg: number;
    targetWeightKg: number;
    gender: _Gender;
} {
    return {
        age: value.age,
        heightCm: value.heightCm,
        targetBmi: value.targetBmi,
        weightKg: value.weightKg,
        targetWeightKg: value.targetWeightKg,
        gender: to_candid_Gender_n22(_uploadFile, _downloadFile, value.gender)
    };
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    activityName: string;
    speed: ActivitySpeed;
    durationMinutes: number;
    caloriesBurned: number;
}): {
    activityName: string;
    speed: _ActivitySpeed;
    durationMinutes: number;
    caloriesBurned: number;
} {
    return {
        activityName: value.activityName,
        speed: to_candid_ActivitySpeed_n6(_uploadFile, _downloadFile, value.speed),
        durationMinutes: value.durationMinutes,
        caloriesBurned: value.caloriesBurned
    };
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    female: null;
} | {
    male: null;
} {
    return value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivitySpeed): {
    fast: null;
} | {
    slow: null;
} | {
    moderate: null;
} {
    return value == ActivitySpeed.fast ? {
        fast: null
    } : value == ActivitySpeed.slow ? {
        slow: null
    } : value == ActivitySpeed.moderate ? {
        moderate: null
    } : value;
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ActivityEntry>): Array<_ActivityEntry> {
    return value.map((x)=>to_candid_ActivityEntry_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
